services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_api_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ".:/rails"
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: rails
      DATABASE_PASSWORD: password
      DATABASE_NAME: todo_api_development

volumes:
  mysql_data: