version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_api_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - todo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: ./todo_api
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - "./todo_api:/rails"
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: todo_api_development
      RAILS_ENV: development
    networks:
      - todo_network

  frontend:
    build:
      context: ./todo_frontend
      dockerfile: Dockerfile
    volumes:
      - "./todo_frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge