default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: mysql2://root:password@127.0.0.1:3306/

development:
  <<: *default
  url: mysql2://root:password@127.0.0.1:3306/todo_api_development

test:
  <<: *default
  url: mysql2://root:password@127.0.0.1:3306/todo_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>